name: location_tracker_app
description: "A Flutter application designed to track and display the user's location in real-time. It integrates Google Maps and Geolocator for accurate positioning and uses local notifications to alert users about important location updates. This app is perfect for users who need to keep track of their movements, such as for navigation, fitness tracking, or location-based services."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
